### Cadastro
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Kazu",
   "email": "ka@email.com",
   "password": "1gfj3fgj2fj",
   "role": "ADMIN"
}
### Login

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "pati@email.com",
   "password": "1gfj3fgj2fj"
}

### Registro de banda banda 
POST http://localhost:3003/band/registration
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcwNGJkNWNhLTNhZjUtNGQ3Ny05OWVjLWM5ZWE2MDQ1NzIyYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2Mjc0NDk1NywiZXhwIjoxNjYyODMxMzU3fQ.QBZtkJ7AZMcHYYPkSWJdnjih4iYWfeJxHP3D3RrUsUo

{
   "name": "Banda Eva",
   "music_genre": "Axé",
   "responsible": "Ivete"
}

### Detalhes da Banda
GET http://localhost:3003/band/
Content-Type: application/json

{
   "name": "Banda Eva"
}

### Adicionar um show
POST http://localhost:3003/registration
Content-Type: application/json

   {
      "week_day": "Saturday",
      "start_time": "10:00",
      "end_time": "12:00",
      "band_id": "1ffb0108-6766-4804-8792-198516c8b607"
   }

 