### Cadastro
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Kazu",
   "email": "ka@email.com",
   "password": "1gfj3fgj2fj",
   "role": "ADMIN"
}
### Login

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "ka@email.com",
   "password": "1gfj3fgj2fj"
}

### Registro de banda banda 
POST http://localhost:3003/band/registration
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcwNGJkNWNhLTNhZjUtNGQ3Ny05OWVjLWM5ZWE2MDQ1NzIyYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MjkzOTg3MSwiZXhwIjoxNjYzMDI2MjcxfQ.Jk4Yu6OGN_QlvJkP3--tojYAT7bEui2YCXaGAzFelto

{
   "name": "Capital inicial",
   "music_genre": "Rock",
   "responsible": "Dinho"
}

### Detalhes da Banda
GET http://localhost:3003/band/
Content-Type: application/json

{
   "name": "Banda Eva"
}

### Adicionar um show
POST http://localhost:3003/show/registration
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcwNGJkNWNhLTNhZjUtNGQ3Ny05OWVjLWM5ZWE2MDQ1NzIyYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MjkzOTg3MSwiZXhwIjoxNjYzMDI2MjcxfQ.Jk4Yu6OGN_QlvJkP3--tojYAT7bEui2YCXaGAzFelto

   {
      "week_day": "sunday",
      "start_time": 12.00,
      "end_time": 14.00,
      "band_id": "55f7cc8b-0a1e-4188-9f0e-fe497b01afd4"
   }

### Pegar todos os Shows de uma data
GET http://localhost:3003/show/
Content-Type: application/json

{
   "week_day": "saturday"
}

 